### ISSUE TITLE
Connection diagram

### ISSUE THREAD

**Issue by niho06** [UsefulElectronics/la66-lorawan-ttn#1]
Hello UsefulElectronics,

very good design I want to try your board, I see that you uploaded the gerber and components. What worries me is that the PCB does not show the location of each component.

There is a possibility to see your connection diagram or PCB with component positions.

Check, have you tested the range of the module with the type of antenna you are using.

Greetings from Panamá and thanks for your contributions.

**Comment by UsefulElectronics** [comment]
Hello, 

Sorry for the late reply.

I had uploaded this design on PCBWay website. you can find more details there
https://www.pcbway.com/project/shareproject/ESP32S3_LoRaWAN_Communication_with_TTN_Using_LA66_Module_a5ddfb1f.html

If you are planning to place PCB order place it directly from provided link so you can support me.
